services:
  postgres:
    image: postgres:15
    container_name: sst-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sst_db
    ports:
      - "5434:5432"
    volumes:
      - sst_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sst_pgdata:
